[package]
name = "smelling-salts"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
edition = "2018"

license = "MIT OR BSL-1.0"
description = """
Start a thread to wake an async executor when the OS's I/O event notifier
discovers that the hardware is ready.
"""
documentation = "https://docs.rs/smelling-salts"
homepage = "https://github.com/LordAldaron/smelling-salts/blob/master/changelog.md"
repository = "https://github.com/LordAldaron/smelling-salts"
readme = "README.md"
keywords = ["futures", "platform-agnostic", "cross-platform", "io", "interrupt"]
categories = ["asynchronous", "rust-patterns"]

[badges]
travis-ci = { repository = "LordAldaron/smelling-salts" }
maintenance = { status = "actively-developed" }

[dependencies]

[dev-dependencies]
pasts = "0.0.1"
