# Smelling Salts
#
# Copyright (c) 2020 Jeron Aldaron Lau
# 
# Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
# https://apache.org/licenses/LICENSE-2.0>, or the Zlib License, <LICENSE-ZLIB
# or http://opensource.org/licenses/Zlib>, at your option. This file may not be
# copied, modified, or distributed except according to those terms.

[package]
name = "smelling_salts"
version = "0.1.0"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "Apache-2.0 OR Zlib"

description = """
Start a thread to wake an async executor when the OS's I/O event notifier
discovers that the hardware is ready.
"""
repository = "https://github.com/AldaronLau/smelling_salts"
documentation = "https://docs.rs/smelling_salts"
homepage = "https://github.com/AldaronLau/smelling_salts/blob/master/CHANGELOG.md"
include = ["Cargo.toml", "README.md", "LICENSE-ZLIB", "LICENSE-APACHE", "src/*"]
categories = ["asynchronous", "rust-patterns"]
keywords = ["futures", "platform-agnostic", "cross-platform", "io", "interrupt"]
readme = "README.md"
edition = "2018"

[badges]
travis-ci = { repository = "AldaronLau/smelling_salts" }
is-it-maintained-issue-resolution = { repository = "AldaronLau/smelling_salts" }
is-it-maintained-open-issues = { repository = "AldaronLau/smelling_salts" }
maintenance = { status = "actively-developed" }

[dependencies]

[dev-dependencies]
pasts = "0.3"

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"

[features]
default = []
docs-rs = []
