# Smelling Salts
# Copyright © 2020-2021 Jeron Aldaron Lau.
#
# Licensed under any of:
#  - Apache License, Version 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
#  - MIT License (https://mit-license.org/)
#  - Boost Software License, Version 1.0 (https://www.boost.org/LICENSE_1_0.txt)
# At your choosing (See accompanying files LICENSE_APACHE_2_0.txt,
# LICENSE_MIT.txt and LICENSE_BOOST_1_0.txt).

[package]
name = "smelling_salts"
version = "0.2.3"
authors = ["Jeron Aldaron Lau <jeronlau@plopgrizzly.com>"]
license = "Apache-2.0 OR MIT OR BSL-1.0"

description = """
Start a thread to wake an async executor when the OS's I/O event notifier
discovers that the hardware is ready.
"""
repository = "https://github.com/AldaronLau/smelling_salts"
documentation = "https://docs.rs/smelling_salts"
homepage = "https://github.com/AldaronLau/smelling_salts/blob/master/CHANGELOG.md"
include = ["Cargo.toml", "README.md", "src/*"]
categories = ["asynchronous", "rust-patterns", "api-bindings", "hardware-support", "os"]
keywords = ["futures", "platform-agnostic", "cross-platform", "io", "waker"]
readme = "README.md"
edition = "2018"

[dependencies]

[dev-dependencies]
pasts = "0.7"

[package.metadata.docs.rs]
all-features = true
default-target = "x86_64-unknown-linux-gnu"
